version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - CONFIG_PATH=/app/config.json
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    network_mode: "service:backend"
    restart: unless-stopped
