version: '3.8'

services:
  # vpn_client:
  #   image: linuxserver/wireguard
  #   container_name: wireguard_client
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - ./wireguard:/config
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped
  #   command: sh -c "while true; do ping -c 5 10.8.0.1; sleep 1800; done"

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./config.json:/app/config.json
    environment:
      - CONFIG_PATH=/app/config.json
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - PORT=8888
    depends_on:
      - backend
    restart: unless-stopped
